repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
        args: ['--maxkb=30720']
    -   id: check-yaml
        args: ["--unsafe"]
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.6.5
  hooks:
    # Run the linter.
    - id: ruff
      args: [
        --select, E, --select, F, --select, W, --select, B, --select, Q, --select, I,
        --extend-select, UP, --extend-select, W291, --extend-select, I001, --extend-select, F401,
        --fix,
      ]
    # Run the formatter.
    - id: ruff-format
      args: [--line-length=88]
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
    -   id: pyupgrade
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports, --follow-imports=skip]
        additional_dependencies: [tokenize-rt==3.2.0]
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.10
    hooks:
    -   id: bandit
        args: [-lll]
